### PR TITLE
Custom Tooltip

### PR DESCRIPTION
**Pull request by juliephiloche**
Hi Brian,

For the same internal project as zoom and pan, I added a custom popup.

Thanks to merge it with your master.
Julie

I added my custom tooltip. Now you can create a more custom tooltip,
show/hide title, show/hide measures, show/hide additional content in
html (so also use images). To use the dimension or measures (labels and
values) on your title or additional content you use these keywords :
- #dimension_label# : to show the label of the dimension
- #dimension_value# : to show the value of the dimension
- #measure_label_1# : to show the label of the first measure
- #measure_value_1# : to show the value of the first measure
- #measure_label_2# : to show the label of the second measure
- #measure_value_2# : to show the value of the second measure
  You can also change the title color and list of measures color.
  You can also change the background alpha and color.

### CODE REVIEW

**Comment by brianwmunz** [comment]
Hi,
Probably due to the same error I mentioned in the other pull request, this extension fails for me with an error:
" Uncaught SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function."

Also, it would be great if you could update the README to reflect the cool new features you've added once they're fixed.
Thanks

**Comment by juliephiloche** [comment]
Hi Brian,

Thanks to your rapidity.
I've some problems to empty my desktop cache (I don't know how to do it),
so I usually work on the localhost on chrome.
For each feature, I've created a new branch from the master.

The error seems to be a problem of "use strict" in JQuery.
I'm surprised it's on my both branches, I haven't write the same code.
I will solve it.

OK for the README, I'll adapt it for the next pull request.

In exclusivity, I enclose my visualizations, fresh of this morning.
Tooltip :
Zoom :
[image: Images intégrées 1]

​

2015-11-03 17:57 GMT+01:00 Brian Munz notifications@github.com:

**Comment by juliephiloche** [comment]
Hi Brian,

Could you check if the problem is also solved for you?

Thank you.
And sorry for the lost time.

**Comment by brianwmunz** [comment]
Hi Julie,
Great I can see it now, thanks!  Overall, it looks pretty good (a lot of
options and ability to customize!), but there's a few bugs you might have
missed.
1) When I turn on the "Show Title" option, the pop up no longer shows.
2) When I add text to the "Content(html)" field, the pop up no longer shows
The changes also break the example QVFs, but I'm happy to update those.
It'd be easier since I made them.
Thanks!

**Comment by juliephiloche** [comment]
Hi Brian,

I corrected the error, it was a missing in a function, following my lasted
changes.
I'm not familiar with GitHub (usually works with svn), do you see my commit
without a new pull request ?

Thanks,
Julie

2015-11-05 15:43 GMT+01:00 Brian Munz notifications@github.com:

**Comment by brianwmunz** [comment]
Yes I get notified.  I'll check it out, thanks!

**Comment by juliephiloche** [comment]
Hi Brian,

I enclose three screenshot of the settings for your snail.
I haven't the same colors because I don't know your "old" color settings
and what snail.svg you use.

However, I've a color problem with IE. I don't know if it's an old problem
or if I added it with my changes.
The fourth screen is the result in IE.
And I've an error : 'Unable to get property 'length' of undefined or null
reference" in require.js.

Another problem with the scroll.

Do you have an idea about the compatibility or not of some JS functions in
IE ?

Thank you,
Julie

[image: Images intégrées 5][image: Images intégrées 6]
[image: Images intégrées 7][image: Images intégrées 8]

2015-11-06 18:00 GMT+01:00 Brian Munz notifications@github.com:

**Comment by juliephiloche** [comment]
2016-01-15 16:08 GMT+01:00 Julie Philoche julie.philoche.dev@gmail.com:

**Comment by juliephiloche** [comment]
This is how to do in the next version...

​

2016-01-19 12:04 GMT+01:00 Julie Philoche julie.philoche.dev@gmail.com:

**Comment by juliephiloche** [comment]
Hi Brian,

This is my problem with IE 11.0.26.
On the right site, my sense desktop, on the left the same app opened with
ie.
Do you have any idea ?
And of course, no error in the console (F12).

Thank you for your help,
Julie

​
​

2016-01-19 12:17 GMT+01:00 Julie Philoche julie.philoche.dev@gmail.com:

**Comment by juliephiloche** [comment]
In fact, it exists an error (after refresh with console opened), but I
don't know how to solve it cleanly...

​

2016-01-19 14:50 GMT+01:00 Julie Philoche julie.philoche.dev@gmail.com:

**Pull request merged**
